-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 17:09:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cars
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cars` ;

-- -----------------------------------------------------
-- Schema cars
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cars` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cars` ;

-- -----------------------------------------------------
-- Table `cars`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cars`.`Cars` ;

CREATE TABLE IF NOT EXISTS `cars`.`Cars` (
  `VIN` VARCHAR(45) NOT NULL,
  `manufacturer` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`VIN`),
  UNIQUE INDEX `VIN_UNIQUE` (`VIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cars`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cars`.`Customers` ;

CREATE TABLE IF NOT EXISTS `cars`.`Customers` (
  `customer_ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(20) -- NOT NULL
  ,
  `email` VARCHAR(45) -- NOT NULL
  ,
  `address` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_code` INT NULL,
  PRIMARY KEY (`customer_ID`)-- ,
  -- UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  -- UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cars`.`Salespersons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cars`.`Salespersons` ;

CREATE TABLE IF NOT EXISTS `cars`.`Salespersons` (
  `staff_ID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `store` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_ID`),
  UNIQUE INDEX `staff_ID_UNIQUE` (`staff_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cars`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cars`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `cars`.`Invoices` (
  `invoice_number` INT NOT NULL,
  `date` DATE NOT NULL,
  `Customers_customer_ID` INT NOT NULL,
  `Salespersons_staff_ID` INT NOT NULL,
  `car_VIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`invoice_number`, `Customers_customer_ID`, `Salespersons_staff_ID`, `car_VIN`),
  INDEX `fk_Invoices_Customers_idx` (`Customers_customer_ID` ASC) VISIBLE,
  INDEX `fk_Invoices_Salespersons1_idx` (`Salespersons_staff_ID` ASC) VISIBLE,
  INDEX `fk_Invoices_Cars1_idx` (`car_VIN` ASC) VISIBLE,
  CONSTRAINT `customer`
    FOREIGN KEY (`Customers_customer_ID`)
    REFERENCES `cars`.`Customers` (`customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salesperson`
    FOREIGN KEY (`Salespersons_staff_ID`)
    REFERENCES `cars`.`Salespersons` (`staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Cars1`
    FOREIGN KEY (`car_VIN`)
    REFERENCES `cars`.`Cars` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
