-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 19:52:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab_mysql
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lab_mysql` ;

-- -----------------------------------------------------
-- Schema lab_mysql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab_mysql` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `lab_mysql` ;

-- -----------------------------------------------------
-- Table `lab_mysql`.`Cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab_mysql`.`Cars` ;

CREATE TABLE IF NOT EXISTS `lab_mysql`.`Cars` (
  `VIN_ID` VARCHAR(50) NOT NULL,
  `Manufactures` VARCHAR(20) NULL,
  `Model` VARCHAR(20) NULL,
  `Year` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  PRIMARY KEY (`VIN_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_mysql`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab_mysql`.`Customers` ;

CREATE TABLE IF NOT EXISTS `lab_mysql`.`Customers` (
  `Customer_ID` INT NOT NULL,
  `Name` VARCHAR(20) NULL,
  `Phone_number` VARCHAR(20) NULL,
  `Email` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_mysql`.`Invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab_mysql`.`Invoices` ;

CREATE TABLE IF NOT EXISTS `lab_mysql`.`Invoices` (
  `Invoices_ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Customer_ID` INT NOT NULL,
  `Staff_ID` INT NOT NULL,
  `Cars_VIN_ID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Invoices_ID`, `Staff_ID`, `Customer_ID`, `Cars_VIN_ID`),
  INDEX `fk_Invoices_Customers_idx` (`Customer_ID` ASC) VISIBLE,
  INDEX `fk_Invoices_Salesperson1_idx` (`Staff_ID` ASC) VISIBLE,
  INDEX `fk_Invoices_Cars1_idx` (`Cars_VIN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Invoices_Customers`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `lab_mysql`.`Customers` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Salesperson1`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `lab_mysql`.`Salesperson` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Cars1`
    FOREIGN KEY (`Cars_VIN_ID`)
    REFERENCES `lab_mysql`.`Cars` (`VIN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_mysql`.`Salesperson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lab_mysql`.`Salesperson` ;

CREATE TABLE IF NOT EXISTS `lab_mysql`.`Salesperson` (
  `Staff_ID` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Store` VARCHAR(5) NULL,
  PRIMARY KEY (`Staff_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
